name: Build and Push Docker Image

on:
  push:
    branches:
      - master  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Toma el código de la rama especificada

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1  # Configura Docker Buildx

    - name: Log in to Docker Hub
      uses: docker/login-action@v1  # Autentica en Docker Hub
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Usa el secreto para el nombre de usuario de Docker Hub
        password: ${{ secrets.DOCKER_PASSWORD }}  # Usa el secreto para la contraseña/token de Docker Hub

    - name: Build and push Docker image
      run: |
        docker buildx build --build-arg DB_SERVER=${{ secrets.DB_SERVER }} \
                            --build-arg DB_DATABASE=${{ secrets.DB_DATABASE }} \
                            --build-arg DB_USERNAME=${{ secrets.DB_USERNAME }} \
                            --build-arg DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
                            --build-arg GMAIL_CREDENTIALS_JSON=${{ secrets.GMAIL_CREDENTIALS_JSON }} \
                            --build-arg GMAIL_TOKEN_JSON=${{ secrets.GMAIL_TOKEN_JSON }} \
                            --build-arg GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} \
                            --build-arg GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }} \
                            --build-arg GOOGLE_REFRESH_TOKEN=${{ secrets.GOOGLE_REFRESH_TOKEN }} \
                            --build-arg GOOGLE_TOKEN=${{ secrets.GOOGLE_TOKEN }} \
                            -t francogaris/challenge_meli:latest .  
        docker push francogaris/challenge_meli:latest