name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/mi-imagen-app:latest

    - name: Run Docker container (optional, for testing)
      run: docker run --rm \
        -e DB_DATABASE="${{ secrets.DB_DATABASE }}" \
        -e DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
        -e DB_SERVER="${{ secrets.DB_SERVER }}" \
        -e DB_USERNAME="${{ secrets.DB_USERNAME }}" \
        -e GMAIL_CREDENTIALS_JSON="${{ secrets.GMAIL_CREDENTIALS_JSON }}" \
        -e GMAIL_TOKEN_JSON="${{ secrets.GMAIL_TOKEN_JSON }}" \
        -e GOOGLE_CLIENT_ID="${{ secrets.GOOGLE_CLIENT_ID }}" \
        -e GOOGLE_CLIENT_SECRET="${{ secrets.GOOGLE_CLIENT_SECRET }}" \
        -e GOOGLE_REFRESH_TOKEN="${{ secrets.GOOGLE_REFRESH_TOKEN }}" \
        -e GOOGLE_TOKEN="${{ secrets.GOOGLE_TOKEN }}" \
        ${{ secrets.DOCKER_USERNAME }}/mi-imagen-app:latest
